baseURL: "https://barath.xyz/"
title: "barath.xyz"
theme: "PaperMod"
paginate: 5

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  defaultTheme: dark
  disableThemeToggle: false
  
  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  showtoc: true
  tocopen: true
  
  # Homepage Configuration
  homeInfoParams:
    Title: "hi there wave.."
    Content: |
      AI product engineer building application on large language models and generative AI. Currently exploring model fine-tuning and multimodal applications.

  social:
    - name: github
      url: "https://github.com/barat-paim"
    - name: substack
      url: "https://thusai.substack.com"
    - name: huggingface
      url: "https://huggingface.com"

menu:
  main:
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 10
    - identifier: tea
      name: Tea
      url: /tea/
      weight: 20
    - identifier: about
      name: About
      url: /about/
      weight: 30

# For better code highlighting
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
