baseURL: "https://barath.xyz/"
languageCode: "en-us"
title: "barath.xyz"
theme: "PaperMod"

# Add menu items
menu:
  main:
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 10
    - identifier: tea
      name: Tea
      url: /tea/
      weight: 20
    - identifier: about
      name: About
      url: /about/
      weight: 30

params:
  # Keep your existing params
  homeInfoParams:
    Title: "hi there wave.."
    Content: |
      AI product engineer building application on large language models and generative AI. Currently exploring model fine-tuning and multimodal applications.

  socialIcons:
    - name: "GitHub"
      url: "https://github.com/barat-paim"
    - name: "Hugging Face"
      url: "https://huggingface.com"
    - name: "LinkedIn"
      url: "https://linkedin.com/in/yourusername"

  # Add these PaperMod specific settings
  ShowBreadCrumbs: true
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowToc: true
  
  # Archives page settings
  archives:
    enable: true
    path: "/archives"
    title: "Archives"
