baseURL: "https://barath.xyz/"
languageCode: "en-us"
title: "barath.xyz"
theme: "PaperMod"

params:
  homeInfoParams:
    Title: "hi there wave.."
    Content: |
      AI product engineer building application on large language models and generative AI. Currently exploring model fine-tuning and multimodal applications.

      Recent Projects: Model Fine-tuning LLaMA 3.2 (1B) on SQuAD dataset, talkingTom: News Agent with Speech & Visuals using DALL-E, ElevenLabs.

      Previously: pm/spm in regtech, patientcare, social commerce.

      Education: Stanford, IIMB, IITM.

  social:
    - name: "GitHub"
      url: "https://github.com/barat-paim"
    - name: "Hugging Face"
      url: "https://huggingface.com"
    - name: "LinkedIn"
      url: "https://linkedin.com/in/yourusername"
