baseURL: "https://barath.xyz/"
languageCode: "en-us"
title: "My New Hugo Site"
theme: "PaperMod"

params:
  homeInfoParams:
    Title: Hi there wave
    Content: Can be Info, links, about...

  social:
    - name: "GitHub"
      url: "https://github.com/barat-paim"
    - name: "LinkedIn"
      url: "https://linkedin.com/in/yourusername"
